version: "2.2"

services:
 cineweb-user-api:
  container_name: cineweb-user-api
  image: public.ecr.aws/m7x6b7n4/cineweb-user-api-v2:latest
  environment:
  - PORT=80
  ports:
  - 80:80
  build:
   context: .
   dockerfile: Dockerfile